### ISSUE TITLE
不支持5.1 Config::get() ?

### ISSUE THREAD

**Issue by SifuLi** [fw6669998/Thinkphp5-Plugin#1]
使用行式：
use think\facade\Config;

.....

Config::get();  // 没有提示

**Comment by fw6669998** [comment]
请问你用的是哪个版本的phpstorm

**Comment by fw6669998** [comment]
以文件名为前缀的配置还暂未支持,后续将会完善

**Comment by SifuLi** [comment]
PhpStorm 2018.3 EAP
Build #PS-183.2153.44, built on September 5, 2018
JRE: 1.8.0_152-release-1293-b10 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Config::get();  这种静态方式调用，都没提示

**Comment by SifuLi** [comment]
最新版，config有提示了，

use think\facade\Route;
Route::get() 路由 facade静态方式调用，还没提示。

**Comment by fw6669998** [comment]
今天修改了些, route应该有提示了

**Comment by SifuLi** [comment]
谢谢
