### ISSUE TITLE
模型的层级显示

### ISSUE THREAD

**Issue by skyvzla** [fw6669998/Thinkphp5-Plugin#16]
![image](https://user-images.githubusercontent.com/19506536/70507494-6f3be880-1b67-11ea-9578-374c64ff02b8.png)
无法提示层级的模型
![image](https://user-images.githubusercontent.com/19506536/70507537-8975c680-1b67-11ea-9e14-e68626fbc54f.png)
希望添加一下，谢谢！

**Comment by fw6669998** [comment]
添加了, 试下最新版
https://github.com/fw6669998/Thinkphp5-Plugin/blob/master/plugin.jar

**Comment by skyvzla** [comment]
谢谢

**Comment by skyvzla** [comment]
可以了
